[package]
name = "espup"
version = "0.10.1-dev"
authors = ["Sergio Gasquez Arcos <sergio.gasquez@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/esp-rs/espup"
description = """
Tool for installing and maintaining Espressif Rust ecosystem.
"""
keywords = ["cli", "embedded", "esp", "esp-rs", "xtensa"]
categories = ["command-line-utilities", "development-tools", "embedded"]
rust-version = "1.71.1"

[dependencies]
async-trait = "0.1.74"
clap = { version = "4.4.11", features = ["derive", "env"] }
clap_complete = "4.4.4"
console = "0.15.7"
directories = "5.0.1"
env_logger = "0.10.1"
flate2 = "1.0.28"
guess_host_triple = "0.1.3"
log = "0.4.20"
miette = { version = "5.10.0", features = ["fancy"] }
regex = "1.10.2"
reqwest = { version = "0.11.22", features = ["blocking"] }
retry = "2.0.0"
serde_json = "1.0.108"
strum = { version = "0.25.0", features = ["derive"] }
tar = "0.4.40"
tempfile = "3.8.1"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
tokio-retry = "0.3.0"
update-informer = "1.1.0"
xz2 = "0.1.7"
zip = "0.6.6"

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10.61", features = ["vendored"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"
winapi =  { version = "0.3.9", features = ["winuser"] }

[dev-dependencies]
assert_cmd = "2.0.12"

[package.metadata.binstall]
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ archive-format }"

[profile.release]
lto = "thin"
strip = true
