[package]
name = "espup"
version = "0.3.3-dev"
authors = ["Sergio Gasquez Arcos <sergio.gasquez@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/esp-rs/espup"
description = """
Tool for installing and maintaining Espressif Rust ecosystem.
"""
keywords = ["esp", "esp-rs", "embedded", "cli", "xtensa"]
categories = ["command-line-utilities", "development-tools", "embedded"]
rust-version = "1.64"

[dependencies]
async-trait = "0.1.68"
clap = { version = "4.2.0", features = ["derive"] }
clap_complete = "4.1.5"
console = "0.15.5"
directories = "5.0.0"
env_logger = "0.10.0"
flate2 = "1.0.25"
guess_host_triple = "0.1.3"
log = "0.4.17"
miette = { version = "5.7.0", features = ["fancy"] }
regex = "1.7.3"
reqwest = { version = "0.11.16", features = ["blocking"] }
retry = "2.0.0"
serde_json = "1.0.95"
strum = { version = "0.24", features = ["derive"] }
tar = "0.4.38"
tempfile = "3.5.0"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
tokio-retry = "0.3.0"
toml = "0.7.3"
update-informer = "0.6.0"
xz2 = "0.1.7"
zip = "0.6.4"

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10.50", features = ["vendored"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.50.0"

[dev-dependencies]
assert_cmd = "2.0.11"
assert_fs = "1.0.12"

[package.metadata.binstall]
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ archive-format }"

[profile.release]
lto = "thin"
strip = true
