[package]
name = "espup"
version = "0.2.7-dev"
authors = ["Sergio Gasquez Arcos <sergio.gasquez@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/esp-rs/espup"
description = """
Tool for installing and maintaining ESP Rust environment.
"""
keywords = ["esp", "esp-rs", "embedded", "cli", "xtensa"]
categories = ["command-line-utilities", "development-tools", "embedded"]
rust-version = "1.64"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.2", features = ["derive"] }
flate2 = "1.0.25"
guess_host_triple = "0.1.3"
reqwest = { version = "0.11.14", features = ["blocking"] }
tar = "0.4.38"
zip = "0.6.3"
xz2 = "0.1.7"
console = "0.15.5"
tempfile = "3.3.0"
log = "0.4.17"
env_logger = "0.10.0"
embuild = { version = "0.31.0", features = ["espidf", "git"] }
strum = { version = "0.24", features = ["derive"] }
toml = "0.6.0"
directories = "4.0.1"
serde = { version = "1.0.152", features = ["derive"] }
miette = { version = "5.5.0", features = ["fancy"] }
regex = "1.7.1"
serde_json = "1.0.91"
thiserror = "1.0.38"
update-informer = "0.6.0"
tokio = { version = "1.24.2", features = ["full"] }
async-trait = "0.1.63"
retry = "2.0.0"
tokio-retry = "0.3.0"

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[dev-dependencies]
assert_fs = "1.0.10"
assert_cmd = "2.0.8"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"

[profile.release]
lto = "thin"
strip = true
