name: Test GH API

on: [ push ]

jobs:
  rust_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Rust test
        run: |
          if [[ -z "${GITHUB_TOKEN}" ]]; then
            echo "GITHUB_TOKEN is defined"
          else
            echo "GITHUB_TOKEN is NOT defined"
          fi
          for i in {1..10}
          do
            cargo test test_xtensa_rust_parse_version -- --nocapture
          done
  culr_test:
    runs-on: ubuntu-latest
    steps:
      - name: Curl test
        run: |
          for i in {1..1500}
          do
            curl --request GET \
            --url https://api.github.com/repos/esp-rs/rust-build/releases \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
          done
